---
name: Releasability Status
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - master
      - dogfood-*
      - branch-*

jobs:
  releasability-status:
    name: Releasability status
    runs-on: sonar-xs
    permissions:
      id-token: write
      statuses: write
      contents: read
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@66c21c6a7fc93337b457f44d1590f8a9e1433cf2 # 3.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
